module.exports = [
    {
        _id: '1',
        id: 1,
        name: 'motor 1',
        room_id: 'room 1',
        node_id: 'node 1',
    },
    {
        _id: '2',
        id: 2,
        name: 'motor 2',
        room_id: 'room 1',
        node_id: 'node 1',
    },
    {
        _id: '3',
        id: 3,
        name: 'motor 3',
        room_id: 'room 1',
        node_id: 'node 1',
    },
    {
        _id: '4',
        id: 4,
        name: 'motor 4',
        room_id: 'room 2',
        node_id: 'node 2',
    },
    {
        _id: '5',
        id: 5,
        name: 'motor 5',
        room_id: 'room 2',
        node_id: 'node 2',
    },
    {
        _id: '6',
        id: 6,
        name: 'motor 6',
        room_id: 'room 2',
        node_id: 'node 2',
    },
    {
        _id: '7',
        id: 7,
        name: 'motor 7',
        room_id: 'room 3',
        node_id: 'node 3',
    },
];
